name: Read_build_test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.ServiceBus.Read/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.ServiceBus.Read
      env_var_name_1: HIQ_ServiceBus_Manage_CS
      env_var_name_2: HIQ_ServiceBus_CS
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.HIQ_SERVICEBUS_MANAGE_CS }}
      env_var_value_2: ${{ secrets.HIQ_SERVICEBUS_CS }}