name: Send_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.CrossplatformServiceBus.Send/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.CrossplatformServiceBus.Send
      env_var_name_1: HIQ_ServiceBus_Manage_CS
      env_var_name_2: HIQ_ServiceBus_CS
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.HIQ_SERVICEBUS_MANAGE_CS }}
      env_var_value_2: ${{ secrets.HIQ_SERVICEBUS_CS }}