name: Send_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.ServiceBus.Send/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.ServiceBus.Send
      env_var_name_1: SERVICEBUS_CONNECTIONSTRING
      env_var_name_2: SERVICEBUS_CONNECTIONSTRING_READONLY
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      env_var_value_1: ${{ secrets.SERVICEBUS_CONNECTIONSTRING }}
      env_var_value_2: ${{ secrets.SERVICEBUS_CONNECTIONSTRING_READONLY }}